version: '3'

services:
  # gradle:
  #   image: gradle:6.9.1-jdk11
  #   container_name: gradle6.9.1
  #   environment: 
  #     ROOT: ${ROOT}
  #   volumes: 
  #     - $ROOT/photo-album-api:/photo-album/api
  #     - $ROOT/docker/gradle_clean_build.sh:/photo-album/gradle_clean_build.sh
  #   command: sh /photo-album/gradle_clean_build.sh

  node:
    image: node:lts
    container_name: node
    environment:
      DEPENDENCY: ${DEPENDENCY}
      COMPONENT: ${COMPONENT}
      ACTION: ${ACTION}
      ROOT: ${ROOT}
    volumes: 
      - $ROOT/photo-album-web:/photo-album/photo-album-web
      - $ROOT/docker/ng_prepare_build.sh:/photo-album/ng_prepare_build.sh
    command: sh /photo-album/ng_prepare_build.sh ${ACTION}
    # depends_on:
    #   - gradle

volumes:
  photoAlbumVolumes: