version: '3'
 
services:
  photo-album-api:
    image: openjdk:15
    container_name: photo-album-api
    ports: 
      - 8080:8080
    volumes:
      - ../photo-album-api/build/libs/photo-album-api-1.0.jar:/photo-album/application.jar
    command: ["java", "-jar", "/photo-album/application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork

  photo-album-web:
    image: nginx
    container_name: photo-album-web
    ports:
      - 80:80
    depends_on:
      - photo-album-api
    volumes:
      - ../docker/photo-album.nginx.conf:/etc/nginx/conf.d/default.conf
      - ../photo-album-web/dist/photo-album-web:/usr/share/nginx/html
    networks:
      - frontendNetwork
  
  photo-album-angular:
    image: node:lts
    container_name: photo-album-angular
    ports:
      - 4200:4200
    volumes:
      - ../photo-album-web:/photo-album/photo-album-web
      - ./ng_prepare_serve.sh:/photo-album/ng_prepare_serve.sh
    command: sh /photo-album/ng_prepare_serve.sh
    depends_on:
      - photo-album-api
    networks: 
      - frontendNetwork
  
volumes:
  photoAlbumVolumes:

networks:
  frontendNetwork:
  backendNetwork: